version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg-practical
    environment:
      POSTGRES_PASSWORD: practical
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: